linters-settings:
  lll:
    line-length: 170
linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - depguard
    - dupl
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maligned
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nosnakecase
    - paralleltest
    - revive
    - rowserrcheck
    - scopelint
    - structcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
