linters-settings:
  lll:
    line-length: 170
  cyclop:
    max-complexity: 15
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gci
    - gofumpt
    - nlreturn
    - paralleltest
    - revive
    - testpackage
    - wsl
    - err113
    # deprecated
    - golint
    - maligned
    - deadcode
    - interfacer
    - varcheck
    - nosnakecase
    - ifshort
    - structcheck
    - scopelint
    - gomnd
    - execinquery
