linters-settings:
  lll:
    line-length: 170
linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoglobals
    - gofumpt
    - nlreturn
    - paralleltest
    - revive
    - testpackage
    - wrapcheck
    - wsl
